# Generated by Django 3.2 on 2022-07-13 11:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.IntegerField(default=0)),
                ('gross_profit', models.IntegerField(default=0)),
                ('net_profit', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('number_of_products', models.IntegerField(default=0)),
                ('number_of_orders', models.IntegerField(default=0)),
                ('number_of_customers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shop', models.CharField(blank=True, default='None', max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_tech', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_customized', models.BooleanField(default=False)),
                ('is_ugandan', models.BooleanField(default=False)),
                ('is_tagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shop', models.CharField(blank=True, default='None', max_length=100)),
                ('is_tech', models.BooleanField(default=False)),
                ('is_fashion', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
                ('is_party', models.BooleanField(default=False)),
                ('is_tagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Net_Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=100)),
                ('mtn_name', models.CharField(blank=True, default='None', max_length=100)),
                ('mtn', models.CharField(blank=True, default='Empty', max_length=10)),
                ('airtel_name', models.CharField(blank=True, default='None', max_length=100)),
                ('airtel', models.CharField(blank=True, default='Empty', max_length=10)),
                ('wave_name', models.CharField(blank=True, default='None', max_length=100)),
                ('wave', models.CharField(blank=True, default='Empty', max_length=10)),
                ('vendor_name', models.CharField(blank=True, default='None', max_length=100)),
                ('dates', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('shop', models.CharField(blank=True, default='Pearl', max_length=100)),
                ('date_sold', models.DateTimeField(default=datetime.datetime.today)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='profile')),
                ('phone', models.CharField(blank=True, default='1', max_length=10)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('alternative_Phone', models.CharField(blank=True, default='1', max_length=10)),
                ('shop_name', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('vendor', models.CharField(blank=True, default='None', max_length=100)),
                ('dates', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('del_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='Uploads/products/')),
                ('shop', models.CharField(default=1, max_length=100)),
                ('shop_name', models.CharField(blank=True, default='Pearlmart', max_length=100)),
                ('dates', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('is_best_selling', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_most_viewed', models.BooleanField(default=False)),
                ('is_new_product', models.BooleanField(default=False)),
                ('is_hot_sale', models.BooleanField(default=False)),
                ('is_hot_deal', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_news', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='Order_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('selling_price', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('status', models.BooleanField(default=False)),
                ('ordering_code', models.CharField(default='', max_length=6)),
                ('shop_name', models.CharField(default='', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('selling_price', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('dates', models.DateField(default=datetime.datetime.today)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('status', models.BooleanField(default=False)),
                ('ordering_code', models.CharField(default='', max_length=6)),
                ('shop_name', models.CharField(default='Pearlmart', max_length=6)),
                ('is_accounted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.post')),
            ],
        ),
    ]
