# Generated by Django 2.2 on 2022-06-12 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shop', models.CharField(blank=True, default='None', max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_tech', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_customized', models.BooleanField(default=False)),
                ('is_ugandan', models.BooleanField(default=False)),
                ('is_tagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shop', models.CharField(blank=True, default='None', max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_tech', models.BooleanField(default=False)),
                ('is_fashion', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
                ('is_party', models.BooleanField(default=False)),
                ('is_tagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=100)),
                ('mtn_name', models.CharField(blank=True, default='None', max_length=100)),
                ('mtn', models.CharField(blank=True, default='Empty', max_length=10)),
                ('airtel_name', models.CharField(blank=True, default='None', max_length=100)),
                ('airtel', models.CharField(blank=True, default='Empty', max_length=10)),
                ('wave_name', models.CharField(blank=True, default='None', max_length=100)),
                ('wave', models.CharField(blank=True, default='Empty', max_length=10)),
                ('vendor_name', models.CharField(blank=True, default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='1', max_length=10)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('alternative_Phone', models.IntegerField(blank=True, default='1')),
                ('shop_name', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('vendor', models.CharField(blank=True, default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('image', models.ImageField(upload_to='Uploads/products/')),
                ('shop', models.CharField(blank=True, default='None', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('is_best_selling', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_most_viewed', models.BooleanField(default=False)),
                ('is_new_product', models.BooleanField(default=False)),
                ('is_hot_sale', models.BooleanField(default=False)),
                ('is_hot_deal', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('status', models.BooleanField(default=False)),
                ('ordering_code', models.CharField(default='', max_length=6)),
                ('shop', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.Post')),
            ],
        ),
    ]
