# Generated by Django 3.2 on 2022-12-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_record',
            old_name='date_created',
            new_name='dates',
        ),
    ]
