# Generated by Django 2.2 on 2022-06-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_post_is_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='del_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
