# Generated by Django 2.2 on 2022-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220621_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
