# Generated by Django 3.2 on 2022-07-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_name_payment_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(default='', upload_to='media/profile'),
        ),
    ]
