# Generated by Django 3.2 on 2022-07-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_vendor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordering_code',
            field=models.CharField(default='', max_length=60),
        ),
    ]
