# Generated by Django 3.2 on 2022-07-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_ordering_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_record',
            name='ordering_code',
            field=models.CharField(default='', max_length=60),
        ),
    ]
