# Generated by Django 3.2 on 2022-06-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='dates',
        ),
    ]
