# Generated by Django 3.2 on 2022-06-25 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_date_product_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.IntegerField(default=0)),
                ('gross_profit', models.IntegerField(default=0)),
                ('net_profit', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_products', models.IntegerField(default=0)),
                ('number_of_orders', models.CharField(blank=True, default='', max_length=50)),
                ('customer_location', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
