# Generated by Django 3.2 on 2022-07-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_record_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop_name',
            field=models.CharField(default='Pearlmart', max_length=60),
        ),
    ]
