# Generated by Django 3.2 on 2022-06-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
