# Generated by Django 3.2 on 2022-06-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_accounts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
