# Generated by Django 3.2 on 2022-07-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_shop_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_record',
        ),
    ]
