# Generated by Django 3.2 on 2022-07-19 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_order_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('selling_price', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('status', models.BooleanField(default=False)),
                ('ordering_code', models.CharField(default='', max_length=60)),
                ('shop_name', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
