# Generated by Django 3.2 on 2022-06-27 08:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_alter_accounts_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.IntegerField(default=0)),
                ('gross_profit', models.IntegerField(default=0)),
                ('net_profit', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_products', models.IntegerField(default=0)),
                ('number_of_orders', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Net_Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Order_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('selling_price', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('status', models.BooleanField(default=False)),
                ('ordering_code', models.CharField(default='', max_length=6)),
                ('shop', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('shop', models.CharField(blank=True, default='Pearl', max_length=100)),
                ('date_sold', models.DateTimeField(default=datetime.datetime.today)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
