# Generated by Django 3.2 on 2022-06-29 13:45

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_auto_20220627_0804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debt',
            new_name='Debit',
        ),
        migrations.RenameModel(
            old_name='Order_records',
            new_name='Order_record',
        ),
        migrations.AddField(
            model_name='account',
            name='number_of_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='account',
            name='net_profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_orders',
            field=models.IntegerField(default=0),
        ),
    ]
