# Generated by Django 3.2 on 2022-06-29 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220629_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
