# Generated by Django 3.2 on 2022-06-29 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_vendor_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='dates',
        ),
        migrations.AddField(
            model_name='payment',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
