# Generated by Django 3.2 on 2022-06-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_accounted',
            field=models.BooleanField(default=False),
        ),
    ]
