# Generated by Django 3.2 on 2022-07-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220702_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(blank=True, default='1', max_length=100),
        ),
    ]
