# Generated by Django 3.2 on 2022-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20220704_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.CharField(blank=True, default='Pearlmart', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
