# Generated by Django 3.2 on 2022-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
