# Generated by Django 3.2 on 2022-07-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_record',
            name='shop',
        ),
        migrations.AddField(
            model_name='order_record',
            name='shop_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
