# Generated by Django 3.2 on 2022-07-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20220704_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(default='', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
