# Generated by Django 3.2 on 2022-07-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20220704_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='alternative_Phone',
            field=models.CharField(blank=True, default='1', max_length=10),
        ),
    ]
